version: "1.0"
services:
  web:
    image: bookkeeper-web
    container_name: bookkeeper-web
    build: .
    ports:
      - "8080:8080"
    networks:
      - web
      - database
    depends_on:
      - database
  database:
    image: mysql
    container_name: bookkeeper-database
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: golang
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - database

networks:
  web:
  database: